#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8 on Thu May  8 09:21:18 2014
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.Logo = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/extra/Movies/ctfeval/ctfeval_logo.png", wx.BITMAP_TYPE_ANY))
        self.static_line_13 = wx.StaticLine(self, wx.ID_ANY)
        self.static_line_14 = wx.StaticLine(self, wx.ID_ANY)
        self.openFile = wx.Button(self, wx.ID_ANY, "Select Micrograph...")
        self.label_23 = wx.StaticText(self, wx.ID_ANY, "<- click button to select micrograph")
        self.static_line_9 = wx.StaticLine(self, wx.ID_ANY)
        self.static_line_10 = wx.StaticLine(self, wx.ID_ANY)
        self.label_16 = wx.StaticText(self, wx.ID_ANY, "Voltage Potential (kV)")
        self.text_ctrl_13 = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_RIGHT)
        self.label_17 = wx.StaticText(self, wx.ID_ANY, "Spherical Abberation, Cs (mm)")
        self.text_ctrl_14 = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_RIGHT)
        self.label_18 = wx.StaticText(self, wx.ID_ANY, "Pixel size (Angstroms, A)")
        self.text_ctrl_15 = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_RIGHT)
        self.static_line_11 = wx.StaticLine(self, wx.ID_ANY)
        self.static_line_12 = wx.StaticLine(self, wx.ID_ANY)
        self.label_19 = wx.StaticText(self, wx.ID_ANY, "Defocus 1 (microns, um)")
        self.text_ctrl_16 = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_RIGHT)
        self.label_20 = wx.StaticText(self, wx.ID_ANY, "Defocus 2 (microns, um)")
        self.text_ctrl_17 = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_RIGHT)
        self.label_21 = wx.StaticText(self, wx.ID_ANY, "Angle Astimatism (degrees)")
        self.text_ctrl_18 = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_RIGHT)
        self.label_22 = wx.StaticText(self, wx.ID_ANY, "Amplitude Contrast (0..1)")
        self.text_ctrl_19 = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_RIGHT)
        self.label_24 = wx.StaticText(self, wx.ID_ANY, "enter data")
        self.button_2 = wx.Button(self, wx.ID_ANY, "Process CTF...")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("MyFrame")
        self.button_2.SetBackgroundColour(wx.Colour(255, 198, 191))
        self.button_2.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Cantarell"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        MainSizer = wx.FlexGridSizer(2, 3, 10, 10)
        Input = wx.FlexGridSizer(11, 2, 5, 15)
        MainSizer.Add(self.Logo, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL | wx.ADJUST_MINSIZE, 0)
        Input.Add(self.static_line_13, 0, wx.EXPAND, 0)
        Input.Add(self.static_line_14, 0, wx.EXPAND, 0)
        Input.Add(self.openFile, 0, wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL | wx.ADJUST_MINSIZE, 0)
        Input.Add(self.label_23, 0, wx.ALIGN_CENTER_VERTICAL | wx.ADJUST_MINSIZE, 0)
        Input.Add(self.static_line_9, 0, wx.EXPAND, 0)
        Input.Add(self.static_line_10, 0, wx.EXPAND, 0)
        Input.Add(self.label_16, 0, wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL | wx.ADJUST_MINSIZE, 0)
        Input.Add(self.text_ctrl_13, 0, wx.EXPAND | wx.ALIGN_CENTER_VERTICAL | wx.ADJUST_MINSIZE, 0)
        Input.Add(self.label_17, 0, wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL | wx.ADJUST_MINSIZE, 0)
        Input.Add(self.text_ctrl_14, 0, wx.EXPAND | wx.ALIGN_CENTER_VERTICAL | wx.ADJUST_MINSIZE, 0)
        Input.Add(self.label_18, 0, wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL | wx.ADJUST_MINSIZE, 0)
        Input.Add(self.text_ctrl_15, 0, wx.EXPAND | wx.ALIGN_CENTER_VERTICAL | wx.ADJUST_MINSIZE, 0)
        Input.Add(self.static_line_11, 0, wx.EXPAND, 0)
        Input.Add(self.static_line_12, 0, wx.EXPAND, 0)
        Input.Add(self.label_19, 0, wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL | wx.ADJUST_MINSIZE, 0)
        Input.Add(self.text_ctrl_16, 0, wx.EXPAND | wx.ALIGN_CENTER_VERTICAL | wx.ADJUST_MINSIZE, 0)
        Input.Add(self.label_20, 0, wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL | wx.ADJUST_MINSIZE, 0)
        Input.Add(self.text_ctrl_17, 0, wx.EXPAND | wx.ALIGN_CENTER_VERTICAL | wx.ADJUST_MINSIZE, 0)
        Input.Add(self.label_21, 0, wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL | wx.ADJUST_MINSIZE, 0)
        Input.Add(self.text_ctrl_18, 0, wx.EXPAND | wx.ALIGN_CENTER_VERTICAL | wx.ADJUST_MINSIZE, 0)
        Input.Add(self.label_22, 0, wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL | wx.ADJUST_MINSIZE, 0)
        Input.Add(self.text_ctrl_19, 0, wx.EXPAND | wx.ALIGN_CENTER_VERTICAL | wx.ADJUST_MINSIZE, 0)
        Input.AddGrowableRow(0)
        Input.AddGrowableRow(2)
        Input.AddGrowableRow(6)
        Input.AddGrowableCol(1)
        MainSizer.Add(Input, 1, wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        MainSizer.Add((10, 10), 0, wx.ADJUST_MINSIZE, 0)
        MainSizer.Add(self.label_24, 0, wx.EXPAND | wx.ALIGN_CENTER_VERTICAL | wx.ADJUST_MINSIZE, 0)
        MainSizer.Add(self.button_2, 0, wx.ALL | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 2)
        MainSizer.Add((10, 10), 0, wx.ADJUST_MINSIZE, 0)
        self.SetSizer(MainSizer)
        MainSizer.Fit(self)
        MainSizer.AddGrowableRow(0)
        MainSizer.AddGrowableRow(1)
        MainSizer.AddGrowableCol(1)
        self.Layout()
        # end wxGlade

# end of class MyFrame
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    MyFrame = MyFrame(None, wx.ID_ANY, "")
    app.SetTopWindow(MyFrame)
    MyFrame.Show()
    app.MainLoop()